### ISSUE TITLE
TOP「更新作業を手伝っていただけると幸いです。」

### ISSUE THREAD

**Issue by mtzhiro** [a01sa01to/covid19-ibaraki#1]
## 改善詳細 / Details of Improvement
- リンク先をGithubのページ https://github.com/a01sa01to/covid19-ibaraki などに向ける

## 期待する見せ方・挙動 / Expected behavior
-リンク先が新規Webブラウザウィンドウ／タブで開く

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by a01sa01to** [comment]
あっ…
現在公開しているバージョンでは、新しく [helpus](https://covid19-ibaraki.netlify.com/helpus) というページを作っていて、そのTopのリンクをこのページに飛ばすようにしてあります…

一度ローカルブランチを更新してみてください！
