### ISSUE TITLE
（プロジェクト全体のマネージメント）

### ISSUE THREAD

**Issue by mtzhiro** [a01sa01to/covid19-ibaraki#2]
## 改善詳細 / Details of Improvement
- （ここで議論すべきではないかもしれないが・・）（プロジェクト全体のマネージメントの方法や戦略・タスク管理）
試しにAsanaを使ってみる？
https://app.asana.com/0/1168489081377289

**Comment by a01sa01to** [comment]
それと同じような機能がGitHubのProjectsなる機能がデフォルトで入っているので、Asanaサービスを使う必要はないと思いますが...
作成してみたのでぜひご覧ください↓
https://github.com/a01sa01to/covid19-ibaraki/projects/2
