### ISSUE TITLE
週単位の陽性者増加比と感染経路不明者数推移の増加比を増加分の比率にしてほしい

### ISSUE THREAD

**Issue by foomin10** [a01sa01to/covid19-ibaraki#231]
## 改善詳細 / Details of Improvement
- 週単位の陽性者増加比（全体/第1波/第2波）についてタイトルは「増加比」となっていますが、グラフと説明は「報告数とその前の1週間の報告数の比率」であり、これは実数の比率なので増加分の比率（増加率）ではありません。
- 感染経路不明者数推移（全体/第1波/第2波）も増加比が「1週間前の感染経路不明者数（移動平均値）との比較」となっていますので同様です。

## 期待する見せ方・挙動 / Expected behavior
- 以下のいずれかだと思います。
  - a) 実際にグラフと説明を増加数の比率（増加率）にして、50人から60人になった場合は +20[%]、50人から40人になった場合は -20[%] とする。（増加率はたいてい百分率で表す。）
  - b) タイトルを「陽性者数の前週比」などとする。単位なし比率でも百分率でもかまいませんが、1倍（100%）にラインを引いてわかりやすくしてほしいです。

**Comment by a01sa01to** [comment]
ご提案ありがとうございます。

正しい挙動は「増加率＝増加分÷先週分の平均」といった認識でよろしいでしょうか。

申し訳ないのですが、ただいま立て込んでおりまして、1週間くらいお時間をいただくかもしれませんが差し支えないでしょうか。
早急に修正が必要な場合には、恐れ入りますがご自身で修正のうえ、プルリクエストを送っていただくことも可能です。

お返事お待ちしております。

**Comment by foomin10** [comment]
思うままに書き連ねてしまいましたが、これ東京都の表記ですね。長い間変わってないので私の感覚が間違ってるかもしれません。

東京都の方に投げてみますので一旦忘れてください。

##### ちなみに…

どちらもあとから追加されたカードのためか他の対策サイトではほとんど載ってませんでした。
あと東京都の場合、週単位の陽性者増加比はモニタリング項目から外された等の理由で削除されてました。

- 週単位の陽性者増加比
  - 追加 tokyo-metropolitan-gov/covid19#4325
  - 削除予告 tokyo-metropolitan-gov/covid19#4968
  - 削除 tokyo-metropolitan-gov/covid19#5024
- 新規陽性者における接触歴等不明者数
  - 追加 tokyo-metropolitan-gov/covid19#4956

**Comment by a01sa01to** [comment]
ご親切にありがとうございます。
一応こちらのほうでも変更しておきますね。

茨城県版では、パッと見て増減がわかるようにするため、特に理由がない限りは削除はしない方針でいます。
