### ISSUE TITLE
茨城版コロナNextカードを上にもってくる＆各カードを公式表記に合わせる

### ISSUE THREAD

**Issue by foomin10** [a01sa01to/covid19-ibaraki#233]
## 改善詳細 / Details of Improvement
茨城版コロナNextカードを上の方（検査陽性者の状況の次）にもっていきます。茨城版コロナNextが “県民自らの判断で自分の身を守る” ためのものとなっている重要なものだからです。

そして、[東京都対策サイト](https://stopcovid19.metro.tokyo.lg.jp/)のモニタリング項目(1)～(7)のように、カードを茨城版コロナNextの判断指標に合わせてわかりやすくしましょう。これはそれぞれ別に issue を立てて検討したいです。

よろしくおねがいします。

## 期待する見せ方・挙動 / Expected behavior
- カードの順番が検査陽性者の状況の次に茨城版コロナNextになっている。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by a01sa01to** [comment]
改善のご提案ありがとうございます。
カードの順番変えはすぐに対応します。

茨城版コロナNextの指標である
 - 重症病床稼働率
 - 病床稼働率
 - 陽性率
 - 東京都 感染経路不明者数

においては、これまでのデータをリストにしていません。
ですので、こちらもカードにする場合は実装までにものすごく時間がかかるかと思います。
