### ISSUE TITLE
[BUG] グラフ表示されない時がある

### ISSUE THREAD

**Issue by paichi81** [a01sa01to/covid19-ibaraki#235]
## 起こっている問題 / The Problem

グラフの中身が描画がされない条件がある。
全期間、第１波などを切り替えるとカード内のチャートが空状態になっている。

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/4400857/98344378-82e11f00-2056-11eb-9cb4-0f6363c36b2c.png)

## 期待する見せ方・挙動 / Expected Behavior

- タブ切り替えしても、グラフが空欄にならない

## 起こっている問題の再現手段 / Steps to Reproduce

1. 「全期間」表示されている状態から、「第１波」あるいは「第２波」を選択
1.  再度、別期間「全期間」などに切り替え

ただし空表示されているコンポーネント上で、チャートの書き換えを促すあたり（下図矢印）に触ると再描画されます。

![image](https://user-images.githubusercontent.com/4400857/98345041-7610fb00-2057-11eb-9050-0e1ab552e452.png)

## 動作環境・ブラウザ / Environment
- Windows   Chrome / Edge / Firefox
- iPadPro iOS14 Firefox

iPhone12Pro iOS Chromeで確認しましたが、こちらでは再現できませんでした。

**Comment by a01sa01to** [comment]
ご報告ありがとうございます。返信遅れてすみません。
私の環境では、何度か試してみましたが問題の再現ができなかったので、可能であれば修正していただきたいです...。
私のほうでも原因となりそうな箇所を探してみます。

**Comment by paichi81** [comment]
自信ないながらも見るだけ見てみようとおもって最新ソースをcloneしたのですが、warningとerrorが多発してるかんじで図表ページが開けないのですが、なにか設定必要ですか?(/flowとかは開けます)

![image](https://user-images.githubusercontent.com/4400857/98442612-e3508900-2148-11eb-9180-ff234ed6ba28.png)

**Comment by a01sa01to** [comment]
特に設定は必要ないと思います。環境構築は問題ないように見えます。

画像のエラーの一番下に「Please remove the ...」とあるように見えるので、削除して解決するかもしれません。

「現在ご利用できません」のエラーは、何らかのエラーが生じている場合に起こります。
カードによるエラーであれば、お手数ですが1つ1つのカードでエラーが発生するか確かめるのも有効かと。
（1つのカードでエラーが起きると、トップページは「ご利用できません」エラーが出ます）

対策サイトの各カードにある、埋め込みコードのURLの `ibaraki.stopcovid19.jp` 部分を `localhost:3000` に変えることでカードにアクセスできるはずです。
![image](https://user-images.githubusercontent.com/26807394/98443758-d9328880-2150-11eb-93d7-d526109a5618.png)

**Comment by paichi81** [comment]
中間報告です。
とりあえずカードのほう逐次確認してみていますが、カード単位で表示させようとして下記カードでエラーがでます。

- /cards/untracked-rate?embed=true
- /cards/attributes-of-confirmed-cases?embed=true
- /cards/ibaraki-city-table?embed=true
- /cards/number-of-confirmed-cases-by-age?embed=true

いずれも `Cannot read property '$options' of undefined` で、.nuxt/index.js の該当箇所は下記のようです。
```
Object.defineProperty(Vue.prototype, '$nuxt', {
  get() {
    return this.$root.$options.$nuxt
  },
  configurable: true
})
```

上記４カードを、全期間・第１波・第２波のタブからコメントアウトしてみたところ、とりあえず通常どおり図表表示できるところまで出来ました。ただ`npm run dev`で実行しているとき下記エラーも出ます。

```
 ERROR  [hardsource:20c6fd66] Could not freeze ./.nuxt/router.js: Cannot read property 'hash' of undefined    11:02:21
```

ローカル(Windows/Chrome)で試してみましたが、本番環境同様、全期間～第１・２波を行き来するとチャートが空欄になる事象は再現できました。
空欄の状態で、日別・累計ボタンを押すと表示されるので、初期化まわり？ではないかと思いますがどうでしょう。

**Comment by paichi81** [comment]
もう１点。なんらかのイベントで再描画されます、と書きましたが、どうも軸がずれているようです。
↓の状態で目盛り 0 が２つ並んでいます。

![image](https://user-images.githubusercontent.com/4400857/98488370-17709a80-226c-11eb-881f-52349c3deadc.png)

描画されていない状態をVueDevToolsで除くと、time-bar-chartコンポーネントに値は渡っているように見えます。
computedになってないせいで、リアクティブになってないのかとも思いましたが、TimeBarChartのほうはcomputedで値を渡しているようなので、違うと思いますし…。うーん、なんでしょう。

![image](https://user-images.githubusercontent.com/4400857/98488660-d5e0ef00-226d-11eb-8c09-e009de0135f7.png)

**Comment by a01sa01to** [comment]
返信遅れすみません。原因を探してくださりありがとうございます。
私の環境でも同様の症状がおこりました...！
確かに再度初期化する必要があるかもしれませんね。

それと、`npm run dev` の代わりに `yarn dev-no-axe` を試してみてはいかがでしょうか。
というのも、[FOR_DEVELOPERS.md](https://github.com/a01sa01to/covid19-ibaraki/blob/development/FOR_DEVELOPERS.md) では [yarn](https://classic.yarnpkg.com/ja/) が推奨されているためです。
私のほうでは `Cannot read property '$options' of undefined` といったエラーは生じないため、もしかしたら解消されるのでは...？と思いました。

話は変わりますが、paichi81 さんにこのIssueをアサインしても構わないでしょうか。返信いただければ幸いです。

**Comment by paichi81** [comment]
返信できてなくてすいません。
ちょいちょい追っかけてみようと、タブから飛ぶ４つのカードへcomputedで値を渡すべきかな、といろいろやってみようとおもったのですが
途中のコンポーネントが自分が使ったことのない、TypeScriptのコードになってたりと苦戦してます…

**Comment by a01sa01to** [comment]
お久しぶりです。
先日 [サイトの高速化&東京都版をマージ](https://github.com/a01sa01to/covid19-ibaraki/releases/tag/v5.0) をしたのですが、この症状直ってる感じがしたので、ご確認いただければ幸いです。

**Comment by paichi81** [comment]
確認しました。こちらの問題、解決しているようです。
