### ISSUE TITLE
感染経路不明者数推移を整理

### ISSUE THREAD

**Issue by foomin10** [a01sa01to/covid19-ibaraki#237]
## 改善詳細 / Details of Improvement

東京都と違い、茨城県では陽性者を濃厚接触者と濃厚接触者以外に分けているようで、サイト上に感染経路不明者数のことばはありません。

そのため、濃厚接触者以外の表記にしましょう。

```
「濃厚接触者」とは、家族や知人などからの感染の可能性が高い方、クラスターに関係する方を指します。
```

上記の定義も注釈かどこかで参照できるといいかもしれません。

refs: #233 (公式表記に合わせる)

## 期待する見せ方・挙動 / Expected behavior

- カード タイトルを感染経路不明者数推移から「濃厚接触者以外の推移」にする。
- 濃厚接触者数を「濃厚接触者」にする。
  - 数は余計かなと
- 感染経路不明者数を「濃厚接触者以外」にする。
- 感染経路不明者数（7日間移動平均）を「濃厚接触者以外（平均）」にする。
  - 括弧内は長いので注釈読んで分かればいいかなと

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by a01sa01to** [comment]
ご提案ありがとうございます。
近いうちに直しておきます。

それと、このように文章の微調整であるのであれば、ご自身で修正していただきプルリクを送っていただけますと、わざわざIssueを介することなくすぐに反映されますのでよりよいかと思うのですが、いかがでしょう。

**Comment by a01sa01to** [comment]
再度県のサイトを確認しましたが、「濃厚接触者以外」を用いているのは「茨城版コロナNext」くらいであり、ほとんど「新規」で区分されています。
よって、「濃厚接触者以外」ではなく「新規」とすることにします。

参考までに。[茨城県公式サイトにおける「濃厚接触者以外」の検索結果](https://www.pref.ibaraki.jp/search.html?q=%22%E6%BF%83%E5%8E%9A%E6%8E%A5%E8%A7%A6%E8%80%85%E4%BB%A5%E5%A4%96%22&cx=003582114934913409157%3Auopnni-avto#gsc.tab=0&gsc.q=%22%E6%BF%83%E5%8E%9A%E6%8E%A5%E8%A7%A6%E8%80%85%E4%BB%A5%E5%A4%96%22&gsc.page=1)

**Comment by foomin10** [comment]
確かに、茨城県版コロナNextでは「濃厚接触者以外」ですが、他のページでは「新規」なんですね。

県公式サイトがそうならばこのカードは「新規」がいいかもしれませんね…と思いつつも「新規」じゃちょっとわかりにくすぎると思う気はしてます。結局、県公式に表記のない「感染経路不明者」の現状の方がよいのでしょうか。

「濃厚接触者以外」は感染経路不明だけじゃないと思ったのでこの issue をオープンしたんですが。

**Comment by a01sa01to** [comment]
県の定義での「新規」は「①渡航歴がある方、②県外感染の可能性が高い方（帰省等）、③感染経路が不明である方」となっているので、結局「感染経路不明」になる気がします。

試してみましたが、「新規」の表記では分かりづらい気がするので、「感染経路不明」のほうが良いと思います。

**Comment by foomin10** [comment]
公式の表現ではないものの公式が分かりづらいため現状のままということで、クローズいたします。
失礼しました。
