### ISSUE TITLE
「新型コロナウィルスが心配なときに」のページでスクロールがひっかかる

### ISSUE THREAD

**Issue by paichi81** [a01sa01to/covid19-ibaraki#252]
## 起こっている問題 / The Problem
- `新型コロナウイルス感染症が心配なときに` のページで下にスクロールしようとすると、途中でひっかかりる時がある

## 期待する見せ方・挙動 / Expected Behavior
- ひっかからないようにする

## 起こっている問題の再現手段 / Steps to Reproduce
1. かかりつけ医があるときにのイメージ部分でスクロールする
2. スクロールバーは下がるが、しばらく同じ場所で止まる
3. さらに下にさげると、不安におもう方のしたにいきなりジャンプする

## 動作環境・ブラウザ / Environment
- macOS / Windows / iOS
- Chrome / Safari / Edge

**Comment by a01sa01to** [comment]
もしかしたら、東京都版をマージした際に手違いで変な表示になってしまったのかもしれません。
一度戻してみます。

**Comment by a01sa01to** [comment]
開発時は何の問題もないのですが、
![image](https://user-images.githubusercontent.com/26807394/103172884-19350280-489a-11eb-919e-06418f33a24b.png)

静的ファイルにビルドした際に表示がおかしくなるようです。
![image](https://user-images.githubusercontent.com/26807394/103172885-1b975c80-489a-11eb-8cdd-048867348ca8.png)

う～ん、謎すぎます。。。

**Comment by a01sa01to** [comment]
いろいろ試してみましたが、直らなかったため、東京都版に則って県公式サイトにリダイレクトすることにしました。
