### ISSUE TITLE
３月２３日から検査人数のデータがずれた件について

### ISSUE THREAD

**Issue by swsoyee** [a01sa01to/covid19-ibaraki#28]
## 起こっている問題 / The Problem
- 3月23日の日付が二回入力されたため、その以後の検査人数が全て一日ずれました
https://github.com/a01sa01to/covid19-ibaraki/blob/development/data/data.json#L237

## スクリーンショット / Screenshot

<img width="683" alt="スクリーンショット 2020-04-10 12 33 52" src="https://user-images.githubusercontent.com/20528423/78960014-ad521480-7b27-11ea-8693-cc6224d21bf5.png">

確認ソース：
https://www.pref.ibaraki.jp/hokenfukushi/yobo/kiki/yobo/kansen/idwr/information/other/documents/documents/0403_kensa.pdf
![image](https://user-images.githubusercontent.com/20528423/78960056-cfe42d80-7b27-11ea-8c7f-cbea0c882fc8.png)
（赤線が書き間違いました。一番右のカラムの数値の方ご覧ください）

![image](https://user-images.githubusercontent.com/20528423/78960125-0e79e800-7b28-11ea-9959-0e475c34e51d.png)

## 期待する見せ方・挙動 / Expected Behavior
- xxxx(できるだけ簡潔に/as concise as possible)

23日は15、24は71であること

## 起こっている問題の再現手段 / Steps to Reproduce
1. xxx
2. xxx
3. xxx

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by a01sa01to** [comment]
失礼しました。ご指摘ありがとうございます。
以下のコミットにて訂正しました！
https://github.com/a01sa01to/covid19-ibaraki/commit/d79c7ac8fb949af8baef75bd045a601487d7037b
