### ISSUE TITLE
茨城県新型コロナウイルス感染症対策サイトが２つあるので混乱を避けるために１つにまとめてください

### ISSUE THREAD

**Issue by Neko7sora** [a01sa01to/covid19-ibaraki#289]
## 改善詳細 / Details of Improvement
- 茨城県新型コロナウイルス感染症対策サイトが２つあるので混乱を避けるために１つにまとめてください
https://github.com/a01sa01to/covid19-ibaraki @a01sa01to 
https://github.com/BenataY/covid19 @BenataY 

## 期待する見せ方・挙動 / Expected behavior
- `stopcovid19-ibaraki`チームを作成してリポリジリをまとめる ( https://github.com/organizations/new )

**Comment by BenataY** [comment]
@Neko7sora 
状況は理解しました。２点確認させてください。
1. 他都道府県でも複数サイトあるところがありますが、この統一化の動きはどういった動きの一環なのでしょうか。本家covid19内の依頼との解釈であってますか。
2. 両サイトとも茨城県庁からリンクが貼られており、実質的には両サイトとも公認されているとの理解でいます。そのため、状況が複雑なので、調整には時間が必要になると思います。

**Comment by a01sa01to** [comment]
ご意見ありがとうございます。
私としては @BenataY さんと同意見です。
@Neko7sora さん、加えて2点質問させてください。

 - 「混乱を避けるため」とありますが、「混乱」とは具体的にどのようなものでしょうか。<br>「混乱」の深刻度によっては1つにまとめる必要がないかもしれません。
 - Organizationを作成してリポジトリをまとめることによって、「混乱を避ける」以上に見込めるメリットはありますか。<br>私個人としては、県公式ページのリンク更新が必要になったり、サイト閲覧者への説明が必要になったり、コンテンツの修正があったりするなどのデメリットが「混乱を避ける」メリットを大きく上回ってしまう懸念があります。

@BenataY さんのものと合わせて計4点、 @Neko7sora さんご回答いただければと思います。

**Comment by Neko7sora** [comment]
> 他都道府県でも複数サイトあるところがありますが、この統一化の動きはどういった動きの一環なのでしょうか。本家covid19内の依頼との解釈であってますか。
サイトによって情報の維持がされていない（自動的にグラフの更新されていない、2020年の情報のままになっているなど）状態で放置されているリポリジリがあり、いろいろと課題が現状にあります。

統一化の動きについては、
1.  県ごとにまとめることで管理がしやすくなる。
2.  2つのサイトの情報が違うと、混乱が起きてしまう。
3. 2つのサイトが違うリポリジリ上にあり、両方に問題点が見つかった場合に、Issues&Pull requestsしなければならない。
というのがあります。

> 本家covid19内の依頼との解釈であってますか。
本家covid19内の依頼ではなく、本家covid19を開発した"Code for Japan"という団体の"covid19プロジェクト"に参加している人の以来です。


> 両サイトとも茨城県庁からリンクが貼られており、実質的には両サイトとも公認されているとの理解でいます。そのため、状況が複雑なので、調整には時間が必要になると思います。

**Comment by Neko7sora** [comment]
> 「混乱を避けるため」とありますが、「混乱」とは具体的にどのようなものでしょうか。
> 「混乱」の深刻度によっては1つにまとめる必要がないかもしれません。

「混乱」というのは、
1. 両サイトとも茨城県庁からリンクが貼られている状態であり、県民の人々の信頼して両方とも利用している時に2つのサイトの情報が違う状態が起こった場合（実際に情報が違う状態が起こっています）

![image](https://user-images.githubusercontent.com/75793267/110316528-3599ac00-804e-11eb-93d1-feffcf9eae75.png)

![image](https://user-images.githubusercontent.com/75793267/110316536-37fc0600-804e-11eb-8dab-8886a625650f.png)

両サイト同じ更新時刻であるという先入観によって"最終更新"を見ないでスクロールして情報が違っていた場合の混乱

2. もし、片方のサイトが緊急事態宣言が出されている説明があり、もう片方がその説明がなかった場合のとき、片方のサイトのみを見ている人の情報の格差が発生してしまい、緊急事態宣言を知らずに外出してしまい揉め事になってしまう可能性があります。茨城県庁からリンクが貼られている両サイトの情報が違うことがのちに大事になってしまう可能性があります。

**Comment by Neko7sora** [comment]
> 両サイトとも茨城県庁からリンクが貼られており、実質的には両サイトとも公認されているとの理解でいます。そのため、状況が複雑なので、調整には時間が必要になると思います。

リポジトリをまとめるのには時間が必要になります。また、`ibaraki.stopcovid19.jp` `stopcovid19-ibaraki.jp`の片方をドメインと設定した場合、もう片方を設定したドメインにリダイレクトできるようにしてください。

> Organizationを作成してリポジトリをまとめることによって、「混乱を避ける」以上に見込めるメリットはありますか。
私個人としては、県公式ページのリンク更新が必要になったり、サイト閲覧者への説明が必要になったり、コンテンツの修正があったりするなどのデメリットが、メリットを大きく上回ってしまう懸念があります。

リポジトリをまとめることによって、
1. 両サイト表記が異なる状態 --> 表記を統一

|  ibaraki.stopcovid19.jp |  stopcovid19-ibaraki.jp |
| ---- | ---- |
|  「茨城県公式サイト」 |  「茨城県庁HP」 |
|  「お問い合わせ先・県内保健所一覧」 |  「各保健所相談窓口」 |
など

2. "最新のお知らせ"が両サイトとも異なる -->お知らせを統一
`stopcovid19-ibaraki.jp`の方が県民のためになるお知らせをしていて、"最新のお知らせ"を見ただけで県についての情報が分かるようになっている。もう片方のサイトは、"最新のお知らせ"を見ただけでは県についての情報をつかみづらくなっている。
両サイトの最新の情報に差が発生している状態にある。

**Comment by BenataY** [comment]
丁寧なご返信ありがとうございます。
基本的に2つあってもデメリットが多いのは仰る通りだと思います。特にユーザ側から見ると混乱の元となるのは仰る通りだと思います。

ただ、もう少し検討が必要だと思っている点として、長期的な安定した運用を考える必要があると思ってます。
都のサイトですとエンジニアがたくさんいますので必要ない心配かもしれませんが、茨城県の場合は数名のエンジニアしか携わってないと思いますので、極端な話、あとは任せますので全部そちらにリダイレクトしますにしてしまうと、何かあった時に更新者がいなくなってしまうリスクが増えてしまうと思います。そして、それこそ茨城県にとって不利益だと思います。
（もっと言うと少ないリソースなら尚更二重管理の状況は勿体無いと思いますが）

私個人としては、あまりサイトの保持に固執はない反面、ここまで運用してきた以上、コロナがキチンと落ち着くまでやり抜きたいなと言う思いもあります。
ご提案いただいている通り、リポジトリを統合してリダイレクトさせて少ないリソースを有効活用するのが、運用面や利便性の上でベターな方向性だと思いますので、一度当事者間で調整させてください。

**Comment by a01sa01to** [comment]
@Neko7sora さん、丁寧なご説明ありがとうございます。

私も @BenataY さんと同様、コロナが落ち着くまでやり抜きたいという思いがあります。
茨城県版のリポジトリでは他都道府県版（特に東京都版）とは異なり、コントリビューターが少ないのは事実です。 
@BenataY さんがご指摘いただいている通り、何かあったときに少人数で進めるというのはリスクがあります（現在実質1人で運用している状況ですが）。
挙げてくださったメリットや現状を鑑みると、統合したほうが良いかというのが私の率直な意見です。

@BenataY さん、よろしければ調整して統合の準備を進めたいと思います。調整はIssue上で行うか、メールなど別のツールを用うか、ご返信いただければ幸いです。

---

蛇足ですが @Neko7sora さん、Code for Japanの `proj-stopcovid19jp` チャンネルにこの議題を投げかけてみてはいかがでしょうか。
他県のリポジトリを見たところ、Issueタブがなかったり、ほとんど自動化してしまっていたりするものがありました。
私個人としては、Code for Japanのチャンネルに投げかけたほうが周知はできるかと考えます。

**Comment by wataruoguchi** [comment]
長野県版コントリビューターです。参考までに：https://github.com/Stop-COVID19-Nagano/covid19/issues/182

**Comment by a01sa01to** [comment]
@wataruoguchi さん、ありがとうございます。拝見させていただきました。

> 私は各々が今までにかけてきた時間や労力は評価されるべきですし、非中央集権的な組織だからこそ類似サービスが複数立ち上がることは十分に予想されており、そこに問題を感じていません。
> これまでにいくつもの全国版まとめサイトが作られてきましたが、いずれのプロジェクトにおいても一つの自治体に複数のサイトが存在することに非を唱えられた事はないと記憶しています。また、本件が課題として挙げられたことも、議論を見たことも記憶にありません。（起票者ご本人の発言は確認しています。）

は、まさにおっしゃる通りだと思います。私も同一自治体内に複数サイトがあってもよいと思っています。

ただ、ここのIssueに挙がっているコメントから、統合するメリットが大きいのかなと個人的には考えていますし、 @BenataY さん側も
>ご提案いただいている通り、リポジトリを統合してリダイレクトさせて少ないリソースを有効活用するのが、運用面や利便性の上でベターな方向性だと思います

と、お互い統合をする方向で検討していると認識しています。

**Comment by Neko7sora** [comment]
> > 本家covid19内の依頼との解釈であってますか。
> ~~本家covid19内の依頼ではなく、本家covid19を開発した"Code for Japan"という団体の"covid19プロジェクト"に参加している人の依頼です。~~
個人の見解です。(誤解を招く恐れのある指摘があったため)

誤解を招くという指摘があったため、コメントを編集しました。

**Comment by BenataY** [comment]
長野県版の議論を読ませて頂きました。非常に参考になりました。
長野県版で議論されていた内容もごもっともな内容だと思ってまして、実際その通りだと思います。

複数サイト存在すること自体が問題あるかと言われれば、必ずしも問題だとは私も思ってません。
ただ、今回のご提案はすごくいいきっかけを与えてくれたなと思っていまして、私自身サイトを約１年間運用してきて、その大変さはよく理解しているので、同じ方向を向いて協力できそうと言う前提があるのであれば、統合するメリットはあるのかなと思ってます。
お話を拝見していて、私も @a01sa01to も県民のために少しでも貢献できたらと言う志の部分と長期的な運用のビジョンが似ているのかなと思っているので、 @a01sa01to がよろしいのであれば、前向きに検討させて頂きたいと思っている次第です。

@a01sa01to さん
返信遅くなってしまい申し訳ありません。ぜひ一度、一緒に検討させてください。
最終的にissueやメール等で調整していくのは良いと思います。
ただ、まず同じビジョンでやれそうかを確認する必要があると思ってまして、一度Zoom等でお互いの考えを会話できたらと思っているのですが、如何でしょうか。（顔出しなしでも構いません）

**Comment by a01sa01to** [comment]
> ただ、まず同じビジョンでやれそうかを確認する必要があると思ってまして、一度Zoom等でお互いの考えを会話できたらと思っているのですが、如何でしょうか。（顔出しなしでも構いません）

@BenataY さん、返信ありがとうございます。
私もお互いに意見を交換する必要があると考えていました。ぜひお願いします。

私のほうは15-19日であれば基本予定が空いていますので、 @BenataY さん側の予定に合わせていただいて構わないのですが、いかがでしょうか。

**Comment by BenataY** [comment]
@a01sa01to さん
21:00からとかでも大丈夫でしょうか？それであれば私もいつでも大丈夫ですが、選んで良いのであれば、17(水)にして頂けると助かります。

**Comment by a01sa01to** [comment]
@BenataY さん、では17日の21:00からでお願いします！

**Comment by BenataY** [comment]
@a01sa01to 
こちらでお願いします

トピック: 茨城版covid19サイトの相談
時間: 2021年3月17日 09:00 PM 大阪、札幌、東京

Zoomミーティングに参加する
https://us02web.zoom.us/j/83542318093

**Comment by a01sa01to** [comment]
@BenataY こちらでお願いします。

トピック: 茨城版 COVID-19 サイト 相談 (2)
時間: 2021年3月22日 21:00 大阪、札幌、東京

Zoomミーティングに参加する
https://us05web.zoom.us/j/82502778100

**Comment by BenataY** [comment]
パスコード設定されていて入れないですね。
パスコード教えて貰うか、部屋は作ったのでこちらに入れませんか？

トピック: ibaraki covid19
時間: 2021年3月22日 09:00 PM 大阪、札幌、東京

Zoomミーティングに参加する
https://us02web.zoom.us/j/84343008795

ミーティングID: 843 4300 8795

**Comment by a01sa01to** [comment]
遅れてすみません、部屋に入りました。

**Comment by BenataY** [comment]
サイトを統合しました。
これにより茨城県版は１サイトのみの運用になります。

@a01sa01to 
色々とご対応ありがとうございました。
引き続き宜しくお願いします。

**Comment by a01sa01to** [comment]
@Neko7sora さん、サイトが統合されたため、このIssueはCloseします。

@BenataY さん、今後ともよろしくお願いします。
