### ISSUE TITLE
県内の感染状況の市町村別数値の表示が欲しい

### ISSUE THREAD

**Issue by Kunado** [a01sa01to/covid19-ibaraki#29]
## 改善詳細 / Details of Improvement
- 東京都は都の公式 Web  サイトで表形式で区市町村別の感染者数を掲示しているが、茨城県は県の公式 Web サイトでは個別の発生事例 PDF ファイルへのリンクがあるのみで県内での地域別の感染状況が把握しづらい。
- このページでそのような表示ができたらどうか。

## 期待する見せ方・挙動 / Expected behavior
<img width="982" alt="スクリーンショット 2020-04-15 8 05 17" src="https://user-images.githubusercontent.com/20355551/79282363-f0c5cd80-7eef-11ea-9165-e363a7b3dd1b.png">
参考: [新型コロナウイルスに関連した患者の発生について（第199報）東京都福祉保健局](https://www.fukushihoken.metro.tokyo.lg.jp/hodo/saishin/corona199.html)

### 実装方針の検討
- HTML table Element
   - 最も対応が簡単かと思われる。(梅プラン)
- 感染状況のマップを SVG Element で描画し各市町村にホバー / クリックすると市町村別の状況が確認できるような方式。
   - 県内のどの地域で感染が拡大しているかを把握するには表よりも感染数でヒートマップのように色付けするなどグラフィカルに把握できる手段があるとベターだと思う。
   - 実装はやや重めか。(松プラン)

まずは梅から実装し、余力があれば松もやるというのが正攻法か。

#### ほか検討事項
- 市区町村別の感染状況のデータは存在するか。
   - 既存のデータに対する処理が必要か。
- 回復状況を反映させるか。
   - 発生 -> 入院中 -> 退院済み のようにデータを反映させるか。
   - そういうデータが存在するか。
      - 茨城県の Web ページのみを確認すると発生についてのデータしか掲載されていない？
- 使用可能な茨城県の SVG 画像はあるか。
   - 市区町村が違う XML タグで描画されているとベター。
- どこに掲載するか。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by a01sa01to** [comment]
ご提案ありがとうございます！

## 検討事項について
 > まずは梅から実装し、余力があれば松もやるというのが正攻法か。<br>

その通りだと思います。作業を進めていきます。

---

> 市区町村別の感染状況のデータは存在するか。

存在しますが、「○○保健所管内」というものもあるため、これについては「○○保健所管内」として扱おうと思います。

---

> 回復状況を反映させるか。
> そういうデータが存在するか。

存在します。ただし、「入院予定」と書かれている患者もおり、その方々については県公式でのデータ更新が見られないので、「入院中・入院予定」とまとめるのがbetterかと。<br>
参考: [新型コロナウイルス感染症患者の退院の状況／茨城県](https://www.pref.ibaraki.jp/1saigai/2019-ncov/taiin.html)

---

> 使用可能な茨城県の SVG 画像はあるか。

Wikipediaにありました。[ファイル:茨城県地域区分図.svg - Wikipedia](https://ja.wikipedia.org/wiki/%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB:%E8%8C%A8%E5%9F%8E%E7%9C%8C%E5%9C%B0%E5%9F%9F%E5%8C%BA%E5%88%86%E5%9B%B3.svg)
市区町村が違う XML タグで描画されているようです。

> このメディアは、クリエイティブ・コモンズに示される表示 - 継承 3.0 Unportedのライセンスの下提供されています。

とあるので使用・改変しても問題ないかと思われます。<br>
参考: [Creative Commons — 表示 - 継承 3.0 非移植 — CC BY-SA 3.0](https://creativecommons.org/licenses/by-sa/3.0/deed.ja)

---

> どこに掲載するか。

私個人の考えとしては、新しいカードを作り、トップページに載せたほうが良いかと思います。

**Comment by Kunado** [comment]
早速のご返信ありがとうございますー。
自分で対応するつもりで立てた Issue でしたがそちらで対応してくださるのですね。
私の方でも何かお手伝いできそうなことがあれば言っていただければと思います。

**Comment by a01sa01to** [comment]
ありがとうございます！
何かあればご連絡させていただきますので、その時はまたよろしくお願いします。

**Comment by a01sa01to** [comment]
このCommitにて作成しました。
https://github.com/a01sa01to/covid19-ibaraki/commit/2aa3a3518cb08ee6ede3e9efd498656fa2525c74

こちらにて変更をご確認いただければと思います。
https://covid19-ibk-dev.netlify.com/
