### ISSUE TITLE
データ更新の自動化

### ISSUE THREAD

**Issue by Kunado** [a01sa01to/covid19-ibaraki#30]
## 改善詳細 / Details of Improvement
- `data/data.json` は県公式 Web サイトの PDF ファイルからデータを取得して手動で更新しているのでしょうか。
- 今であれば GitHub Actions の cron 定期実行処理などで PDF ファイルをパースするなどしてデータを取得する方法が考えられます。
   - PDF をパースするスクリプトを書いたことはありませんが、以下のような事例はあるようです。
   - [RubyでPDFをCSVライクにパースする - Qiita](https://qiita.com/kskinaba/items/550a5b802feba2f8f07e)

## 期待する見せ方・挙動 / Expected behavior
- xxxx(できるだけ簡潔に/as concise as possible)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by a01sa01to** [comment]
ご提案ありがとうございます！

---

> data/data.json は県公式 Web サイトの PDF ファイルからデータを取得して手動で更新しているのでしょうか。

手動更新です。

---

> 今であれば GitHub Actions の cron 定期実行処理などで PDF ファイルをパースするなどしてデータを取得する方法が考えられます。

そうしたいのですが、固定ファイルが [発生状況](https://www.pref.ibaraki.jp/1saigai/2019-ncov/hassei.html) のみで、新規PDFファイルのURLがわからないというか...
さらに、仮にPDFファイルを取得できたとしても、ファイルの形式が一通りではなく、
例えば [102, 103件目](https://www.pref.ibaraki.jp/1saigai/2019-ncov/documents/0412mito45.pdf) のデータあたりだと自動更新では4, 5件目として認識される可能性もあります。

この点から、現段階での自動化は難しいかと...
県公式が形式を固定してくれるとありがたいのですが...

解決案があれば教えていただけると嬉しいです！

**Comment by Kunado** [comment]
> そうしたいのですが、固定ファイルが 発生状況 のみで、新規PDFファイルのURLがわからないというか...

なるほど。
その場合であればまずはじめに [新型コロナウイルス感染症患者の県内の発生状況（報道発表資料）／茨城県](https://www.pref.ibaraki.jp/1saigai/2019-ncov/hassei.html) のページをパースして PDF ファイルへのリンクを取得してから各 PDF ファイルのパースをするという形にすれば良いかと思います。

> さらに、仮にPDFファイルを取得できたとしても、ファイルの形式が一通りではなく、
例えば 102, 103件目 のデータあたりだと自動更新では4, 5件目として認識される可能性もあります。

確かに形式がかなり自由ですねこれは…。基本的にはある形式に準じていると仮定して、 パース処理が Fail したら手動でやるなどの方法でも良いかとは思いますが。
この現状だと投じるリソースに対する見返りが少なくなりそうで少し手は出しにくいかなぁ。

> 県公式が形式を固定してくれるとありがたいのですが...

その通りですね。福井県ではオープンデータとして公開しているみたいなので、茨城県もこうしてくれればいいんですが。
[新型コロナウイルス感染症のオープンデータを公開します！ | 福井県ホームページ](https://www.pref.fukui.lg.jp/doc/toukei-jouhou/covid-19.html)

**Comment by a01sa01to** [comment]
提案として、県に問い合わせてみました。
返信が前向きなものになることを祈るばかりです...

**Comment by a01sa01to** [comment]
お久しぶりです。
今更ながら、進展があったのでご報告致します。

オープンデータに対して、県の返答は以下の通りでした。
> 編集や検証を容易にするため，オープンデータの重要性は承知しており，公開している自治体があることも承知しております。
> しかし，本県では複数項目をcsv形式では管理しておらず（※），現時点ではオープンデータの公開はできかねます。
> ※基本的にエクセル管理ですが，１つのセルに入退院の状況等を書き込んでいて分離が困難であったり，事例によっては別ファイルにあったりします。

ということですので、県からオープンデータを提供していただいての自動化は難しそうです。

私がオープンデータを作成し、公開しても構わないか尋ねたところ、問題ないとお返事をいただきました。
そこで、（結局は手動ですが）オープンデータを作成し、半自動化しようと思います。
まだ作成途中ですが、以下がデータとなります。
https://docs.google.com/spreadsheets/d/1Htkw2e1De7_jgNgosfUPoGlaOuAgJ_t-IOoawdxBdfk/

長い間お待たせしてすみませんでした。
オープンデータを完成させて公開し、自動化処理を加えたときに、このIssueを閉じさせていただきます。

**Comment by a01sa01to** [comment]
お待たせ致しました。
[オープンデータ](https://docs.google.com/spreadsheets/d/1Htkw2e1De7_jgNgosfUPoGlaOuAgJ_t-IOoawdxBdfk) が完成したため、コミット babf65b にて自動化処理を加えました。
以上にてIssueを閉じさせていただきます。ありがとうございました。
