### ISSUE TITLE
「検査陽性者の状況」の積み上げ棒グラフ表示の追加

### ISSUE THREAD

**Issue by Kunado** [a01sa01to/covid19-ibaraki#36]
## 改善詳細 / Details of Improvement
- 現在の「検査陽性者の状況」はそれぞれの項目の人数が全体の人数に占める割合を一目で判別しづらい表示になっている。
   - 積み上げ棒グラフのような表示であればそれぞれの項目の人数が全体の人数に占める割合を一目で判別できるようになる。
   - オリジナルの東京都版でも同様の表示の仕方をしていますが、このような見せ方に何か理由があるのだろうか。
      -  ~積み上げ棒グラフをあえて使っていない理由があるのだろうか。~ Issue を探してみたものの、同様の趣旨の改善案はなし。
      - 表の作成時からこのような表示をしている模様。 :[表の追加：検査陽性者の状況 · Issue #309 · tokyo-metropolitan-gov/covid19](https://github.com/tokyo-metropolitan-gov/covid19/issues/309) 

## スクリーンショット / Screenshot

- 現在の表示方法
   <img width="563" alt="スクリーンショット 2020-04-19 22 57 53" src="https://user-images.githubusercontent.com/20355551/79689657-3b00d300-8291-11ea-86cb-0158b85cab1b.png">

## 期待する見せ方・挙動 / Expected behavior

- Google Spread Sheet で出力した洗練されていないグラフで申し訳ないですが、イメージとしてはこんなグラフが表示されるような感じです。
   <img width="597" alt="スクリーンショット 2020-04-19 22 58 50" src="https://user-images.githubusercontent.com/20355551/79689681-5a97fb80-8291-11ea-992a-5e8719f72d16.png">
    - この画像で言うと、ラベルや人数の表示位置だとかは見せ方を考えたいです。
    - Chart.js がすでに導入済みのようなので、その中で言えば [Stacked Bar Chart](https://www.chartjs.org/samples/latest/charts/bar/stacked.html) が使えそうです。
      - 「合計」と「入院中 / 死亡 / 退院」の 2 つの項目のみのグラフになるかと思うので、縦の積み上げ棒グラフと言うよりは横向きの積み上げ棒グラフで表示するイメージですが、 Chart.js にそのオプションがあるのかは未確認です。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by a01sa01to** [comment]
ご提案ありがとうございます。
確かにそれぞれの項目の割合がわかりづらいですよね...

---

> Stacked Bar Chart が使えそうです。

私個人としては、[Pie Chart](https://www.chartjs.org/samples/latest/charts/pie.html) でもいいのかなと思いました。
というのも、「陽性患者の属性」で大きく「139人 (2020.04.20 0:00現在)」と書かれているので。
![image](https://user-images.githubusercontent.com/26807394/79691249-51129180-8299-11ea-9903-f8ce8172932c.png)

また、上画像のように合計数も出すことは可能なので、「Pie Chart + 上部の合計数」でもありではないかというのが現段階の、私個人の意見です。

---

> 横向きの積み上げ棒グラフで表示するイメージですが、 Chart.js にそのオプションがあるのかは未確認です。

Stacked Bar Chart ではありませんが、[Horizontal Bar Chart](https://www.chartjs.org/samples/latest/charts/bar/horizontal.html) で代用できるかもしれません。

参考: [chart.jsで積み上げ横棒グラフを描く - Qiita](https://qiita.com/yuba99/items/0442828b876dec67162a)

---

何かあれば連絡いただけると嬉しいです。

**Comment by Kunado** [comment]
早速のご返信ありがとうございます。
> 私個人としては、Pie Chart でもいいのかなと思いました。

データの割合を表現するのによく用いられる円グラフですが、最近はその使用については否定的な意見が見られる印象があります。

* [それでもまだ円グラフを使いますか？ - データ可視化のアイデア帳](https://dataviz.hatenablog.com/entry/2019/02/05/180316)
* [データ視覚化のデザイン #1｜Go Ando / THE GUILD｜note](https://note.com/goando/n/neb6ea35f1da3)

以上での指摘を踏まえると、円グラフを用いたい積極的な理由がない限りは他の可視化の手法を検討すべきかなというのが私の見解です。

> Stacked Bar Chart ではありませんが、Horizontal Bar Chart で代用できるかもしれません。
> 参考: chart.jsで積み上げ横棒グラフを描く - Qiita

こちらはイメージ通りです。問題なく表現できそうですね。

**Comment by a01sa01to** [comment]
返信ありがとうございます。
---
> 最近はその使用については否定的な意見が多く見られる印象があります。

そうだったのですね。知りませんでした。
Horizontal Bar Chart で取り組んでみます。

**Comment by a01sa01to** [comment]
色はさておいて、このように実装してみました。
色以外に何か変更すべき点があれば教えていただければと思います。

![image](https://user-images.githubusercontent.com/26807394/79726261-7816a500-8325-11ea-87fa-ae9853c7ca8a.png)

ホバーすると下のようになります

![image](https://user-images.githubusercontent.com/26807394/79726427-bca24080-8325-11ea-8ac4-b7de1b69da9a.png)
