### ISSUE TITLE
グラフィカルな地図で感染者分布を可視化

### ISSUE THREAD

**Issue by takonasu** [a01sa01to/covid19-ibaraki#37]
## 改善詳細 / Details of Improvement
- せっかく茨城県版とのことなので、茨城県の地図に感染者分布の色付けをおこなうと分かりやすいのではと思います。
- どの市町村でどのくらい感染者がいるのかを一目でわかるように可視化する。
- 例えば、感染者数に応じて市町村に濃淡をつける（例をスクリーンショットの項目で提示します。）

以上の案を思い付きましたのでissueとして共有しておきます。

## スクリーンショット / Screenshot

表示している地図のデータはサンプルです。
イメージとしてはこのような物ができればいいなと思っています。
![image](https://user-images.githubusercontent.com/37821819/79710483-10019800-8300-11ea-81be-b48db54dd99f.png)

## 期待する見せ方・挙動 / Expected behavior
- 市町村ごとのデータがdata/data.jsonにあるため、実現は可能であると思われます。
- SVGに市町村ごとにパスを作成し、data.jsonのデータによって動的にSVGに色付けを行う。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by a01sa01to** [comment]
ご提案ありがとうございます。
とてもいい案ですね。 #29 の松プランと似ていますね。

---

もしスクリーンショットのものが出来上がれば、PRしていただければMergeします。

私も時間があれば取り組んでみます。
製作を手伝っていただけるととても助かります。

一応茨城県の、市町村でタグが分かれているSVGを貼っておきますね。

[ファイル:茨城県地域区分図.svg - Wikipedia](https://ja.wikipedia.org/wiki/%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB:%E8%8C%A8%E5%9F%8E%E7%9C%8C%E5%9C%B0%E5%9F%9F%E5%8C%BA%E5%88%86%E5%9B%B3.svg)

> このメディアは、クリエイティブ・コモンズに示される表示 - 継承 3.0 Unportedのライセンスの下提供されています。

とあるので使用・改変しても問題ないかと思われます。

**Comment by takonasu** [comment]
ご返信ありがとうございます。
私もWikipediaのSVGが適当かと思われます。

私の方でも試行錯誤してみます。
