### ISSUE TITLE
「当プロジェクトをお手伝いいただける方へ」ページでのリンクミス

### ISSUE THREAD

**Issue by paichi81** [a01sa01to/covid19-ibaraki#91]
## 起こっている問題 / The Problem
- 「当プロジェクトをお手伝いいただける方へ」ページにおいて、"プログラム面について"の詳細は「こちらのドキュメント」とリンクされているが、404NotFoundとなる。

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/4400857/81625999-75473580-9435-11ea-99d5-39efa221a013.png)

## 期待する見せ方・挙動 / Expected Behavior
- 正しいリンク先に遷移する
- DEVELOPPERS.mdでなくFOR_DEVELOPPERS.mdとする

## 起こっている問題の再現手段 / Steps to Reproduce
1. 「当プロジェクトをお手伝いいただける方へ」へ遷移
2. プログラム面についての「こちらのドキュメント」をクリック
3. 404NotFound

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by a01sa01to** [comment]
失礼しました！PRありがとうございます。
